# Generated by Django 5.2.3 on 2025-06-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
